#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

soft_fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}

fail () {
  soft_fail
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}

pull_submodules () {
    info 'setup git submodules'
    cd "$DOTFILES_ROOT"
    git submodule init
    git submodule update
    success "git submodules up to date"
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

try_install_file() {
    src=$1
    dst=$2

    if [ -f $dst ] || [ -d $dst ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File already exists: `basename $src`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dst
        success "removed $dst"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dst $dst\.backup
        success "moved $dst to $dst.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $src $dst
      else
        success "skipped $src"
      fi

    else
      link_files $src $dst
    fi
    
}

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
      dest="$HOME/.`basename \"${source%.*}\"`"
      try_install_file "$source" "$dest"
  done
  for source in `find $DOTFILES_ROOT/bin -maxdepth 1 -name \*.bin`
  do
      dest="$HOME/bin/`basename \"${source%.*}\"`"
      try_install_file "$source" "$dest"
  done
}

install_docopt () {
    info 'installing docopt'
  
    if hash docopts 2>/dev/null; then
        success "skipped docopts"
    else
        cd $DOTFILES_ROOT/docopts
        set +e
        pyinstall_out=$( python setup.py install --user 2>&1 )
        pyinstall_success=$?
        set -e
        if [[ $pyinstall_success == 0 ]]; then
            try_install_file $DOTFILES_ROOT/docopts/docopts $HOME/bin/docopts
        else
            soft_fail "error installing docopts. Full output:"
            echo "$pyinstall_out"
            exit
        fi
    fi
}

pull_submodules

# setup_gitconfig
install_dotfiles
install_docopt

# If we're on a Mac, let's install and setup homebrew.
#if [ "$(uname -s)" == "Darwin" ]
#then
#  info "installing dependencies"
#  if . bin/dot > /tmp/dotfiles-dot 2>&1
#  then
#    success "dependencies installed"
#  else
#    fail "error installing dependencies"
#  fi
#fi


echo ''
echo '  All installed!'
